from app import app
from .page import page_routes
from .auth import auth_routes
from .check_user_first import check_user_first_routes
from .user_modify import user_modify_routes
from .user_info import user_info_routes
from .user_log import user_log_routes
from .chatbot import chatbot_routes
from .exercise import exercise_routes